# Generated by Django 4.2.27 on 2026-01-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('message_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
