# Generated by Django 4.2.27 on 2026-01-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='active_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
