# Generated by Django 4.2.27 on 2026-01-28 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_guest_active_session_key_guest_active_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('main_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_guests', to='core.guest')),
            ],
        ),
    ]
