# Generated by Django 4.2.27 on 2026-01-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_extraguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraguest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extraguest',
            name='not_answered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='not_answered',
            field=models.BooleanField(default=True),
        ),
    ]
