# Generated by Django 4.2.27 on 2026-02-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_extraguest_is_rejected_extraguest_not_answered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraguest',
            name='jid',
            field=models.CharField(blank=True, help_text='WhatsApp JID, e.g. 115831006589136@lid or 5511999999999@s.whatsapp.net', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='jid',
            field=models.CharField(blank=True, help_text='WhatsApp JID, e.g. 115831006589136@lid or 5511999999999@s.whatsapp.net', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
