# Generated by Django 4.2.27 on 2026-02-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_extraguest_jid_guest_jid_alter_guest_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(help_text='WhatsApp JID, e.g. 115831006589136@lid or 5511999999999@s.whatsapp.net', max_length=64)),
                ('messages', models.JSONField(blank=True, default=list, help_text='List of conversation messages')),
            ],
        ),
    ]
