# Generated by Django 4.2.27 on 2026-06-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_conversationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_page_photo', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('hero_photo', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('hero_text', models.TextField(default='Quase um carnaval fora de época. Estamos preparando uma comemoração inesquecível e contamos com você!')),
                ('cenourinhas_title', models.CharField(default='Por que "Cenourinhas"?', max_length=255)),
                ('cenourinhas_text', models.TextField(default='Muitos perguntam: "Por que vocês se chamam de Cenourinhas?" Tudo começou com o nosso lema oficial em cada treino de corrida: To Bem Não...')),
                ('cenourinhas_photo', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('sobre_title', models.CharField(default='Sobre o Casal', max_length=255)),
                ('sobre_subtitle', models.CharField(default='Duas metades que se completam', max_length=255)),
                ('sobre_text', models.TextField(default='Ela é uma paulista raiz, dona de uma tatuagem do Banespa no braço e apaixonada por prédios antigos e corridas no asfalto. Ele é tricolor doente pelo Fluminense, fã de moqueca, do mar e de correr com o pé na areia.')),
                ('jornada_title', models.CharField(default='Nossa Jornada', max_length=255)),
                ('jornada_text', models.TextField(default='Um encontro casual no Tinder que virou uma linda história: em pouco tempo já dividíamos o mesmo teto e as aventuras pelo Brasil.')),
                ('jornada_photo', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('assistant_context', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conteúdo do Site',
            },
        ),
    ]
