# Generated by Django 4.2.27 on 2026-07-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pagamento_guest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='presente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.presente'),
        ),
    ]
