# Generated by Django 4.2.27 on 2026-07-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pagamento_nullable_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraguest',
            name='day1_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='extraguest',
            name='day2_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='guest',
            name='day1_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='guest',
            name='day2_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado')], default='pending', max_length=10),
        ),
    ]
