# Generated by Django 4.2.27 on 2026-07-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_whatsappbatch_whatsappbatchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraguest',
            name='message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
