# Generated by Django 4.2.27 on 2026-02-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(help_text='WhatsApp JID, e.g. 115831006589136@lid or 5511999999999@s.whatsapp.net', max_length=64)),
                ('messages', models.JSONField(blank=True, default=list, help_text='List of conversation messages')),
            ],
        ),
    ]
